# Generated by Django 4.0.6 on 2022-08-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_created_at_alter_product_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=50),
        ),
    ]
