# Generated by Django 4.0.6 on 2022-09-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request2', '0002_rename_productvar_requesttype_producto'),
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='productModel',
        ),
    ]
