# Generated by Django 4.0.6 on 2022-09-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_productmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='product',
        ),
    ]
