# Generated by Django 4.0.6 on 2022-09-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttype',
            old_name='productVar',
            new_name='producto',
        ),
    ]
