# Generated by Django 4.0.6 on 2022-09-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request2', '0002_rename_productvar_requesttype_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttype',
            old_name='producto',
            new_name='producto_id',
        ),
    ]
